todo_list/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

end

todo_list/app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :title, presence: true
end

todo_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo_list/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    if request.xhr?
      @complete_todo = Todo.find_by(completed: true)
        render @complete_todo
      else
       @todos = Todo.order('created_at ASC').all
       @todo = Todo.new()
     end
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      if request.xhr?
        render @todo
      else
        redirect_to root_path
      end
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if request.xhr?
     @todo.update(:completed => true)
     render :nothing => true
     else
      redirect_to root_path
    end
  end

  private
    def todo_params
      params.require(:todo).permit(:title, :completed)
    end

end

todo_list/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_list/app/helpers/todos_helper.rb
module TodosHelper
end

todo_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div id="complete"><%= link_to 'Completed'%></div> |
  <%= link_to 'Active'%> |
  <%= link_to 'All'%>
</header>
<body>

<%= yield %>

</body>
</html>

todo_list/app/views/todos/_todo.html.erb
  <p><%= @todo.title %></p>
    <%= form_for @todo, :html => {:id => "complete-item"}, method: 'put', :url => todo_path(@todo.id) do |f| %>
        <%= f.submit 'Complete'%>
    <%end%>

todo_list/app/views/todos/index.html.erb
<h1>TODOS</h1>

<div id ="main">
  <div class="list">
    <% @todos.each do |todo| %>
    <div id="<%=todo.id%>">
      <p><%= todo.title %></p>
        <%= form_for todo, :html => {:id => 'complete-item'}, method: 'put', :url => todo_path(todo.id) do |f| %>
        <%= f.submit 'Complete'%>
      <%end%>
    </div>
    <% end %>
  </div>


  <%= form_for @todo, :html => {:id => 'new_item'} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
  <% end %>
</div>